### ISSUE TITLE
I am trying to use this script to connect to vpn and then disconnect when I need. 

### ISSUE THREAD

**Issue by AshrafAkon** [sjakthol/vpngate-client#2]
I am using your code to fetch and connect to vpngate free vpn servers. but I am running into issues. Can you guys help me with how can I connect to a vpn server and how can I disconnect it and back to normal ? I want to call those functions in my code.

**Comment by sjakthol** [comment]
This script is not really designed for that use case in mind.

What you could try is to modify the part at https://github.com/sjakthol/vpngate-client/blob/master/vpngate-client#L193-L219 which handles 1) connecting, 2) waiting for user input and 3) terminating the VPN at user request (line 214 where we wait for SIGINT).

To control this process from a script, you need to modify the code as follows:
* Store the return value of subprocess.Popen(cmd, start_new_session=True) at https://github.com/sjakthol/vpngate-client/blob/master/vpngate-client#L193 into a variable in your script. This is a handle to the external openvpn process that handles the VPN connection.
* Call terminate_vpn() with the process handle you stored in the first step to terminate the connection (i.e. tell the openvpn process to quit).

You could, for example, modify connect() to do the following:

```python
def connect():
    self.log.info("Connecting to VPN...")
    with tempfile.NamedTemporaryFile(mode="w") as conf:
        self.log.debug("Writing config to %s", conf.name)
        conf.write(self.config)

        cmd = self.build_ovpn_command(conf.name)

        self.log.debug("Executing %s", cmd)
        proc = subprocess.Popen(cmd, start_new_session=True)

        # Wait for the VPN to initialize
        if not self.wait_for_vpn_ready(proc):
            # VPN failed to initialize. Indicate the caller to try the
            # next one.
            return None
        
        # Return the process handle to your script.
        return proc
```

You can then use the code as follows:
```python
# vpn is a reference to the VPN class instance you want to connect to

proc = vpn.connect()
if not proc:
    # Failed to connect, handle error
    pass

# Connection established, do whatever you want
#
# ...
# ...
#
# Terminate connection
vpn.terminate_vpn(proc)

```

I have not tested if that approach work but it should at least provide a starting point for a proper implementation. I'm sure you'll be able to figure a way to make it work.

**Comment by AshrafAkon** [comment]
Thanks @sjakthol  . Solved my problem. Many thanks to you for this project. wish you a great day.
