### ISSUE TITLE
Support L2TP/IPsec

### ISSUE THREAD

**Issue by kekukui** [sjakthol/vpngate-client#3]
**Wow, this is a really nice, useful tool for easy automated connection setup -- but the OpenVPN protocol is very compute-intensive, and CPU overload becomes a data throughput bottleneck on ARM platforms.  Can you add support for L2TP/IPsec to increase performance ?**
_____________________
![image](https://user-images.githubusercontent.com/20834957/80150180-e3f74880-8585-11ea-84ba-400049f2b522.png)

**Comment by sjakthol** [comment]
This project has been designed around OpenVPN. Support for alternative protocols / tools would be very hard to add without increasing the complexity of the codebase. And from what I could gather, L2TP/IPsec is not the easiest thing to setup on a Linux system.

Unfortunately, I'm not actively working on this project any more. I don't really have the time to look into implementing additional features to a tool which works well enough already. However, I'm willing to accept pull requests that implement L2TP/IPsec support in a clean fashion. But I cannot really provide any support with the actual implementation.
