### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by AnmLobby** [sjakthol/vpngate-client#4]
How to run the project? Clone directly to the local, running in pycharm?

**Comment by sjakthol** [comment]
Hi,

Probably the easiest way to run the project is to

1. Clone the repository to your local machine.
2. Install required dependencies (e.g. in Ubuntu by running `sudo apt-get install -y python3 openvpn`)
3. Execute the `vpngate-client` script from the repository: `sudo ./vpngate-client`

Please refer to the project README.md and the output of `./vpngate-client --help` for additional documentation.
